using System;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Threading.Tasks;

namespace Herd.Models
{
    public class Hevent : Microsoft.Azure.Documents.Resource
    {
        /*-------------------------------------------------
        event: unique ID, attached to an admin, viewable by the herd
        -- name: the human-readable name of the event
        -- type: the admin-entered type of event
        -- host: the person in charge of this event
           -- name:
           -- contact:
        -- created: the timestamp that this event was created at
        -- active: the state of the event (e.g. new, started, ended, etc.)
        -- activities: the activities related to the event
           -- description: what the activity is
           -- location: where it's at
           -- timing: when it happens
              -- starts: the datetime it starts
              -- ends: the datetime it ends
        ---------------------------------------------------------*/
        public string Name { get; set; }

        // TODO: make type into an enumaration of constants
        public string Type { get; set; }

        public Hadmin Host { get; set; }

        public DateTime Created { get; set; }

        public string Active { get; set; }

        // list of Hactivity IDs for this event
        public List<string> Activities { get; set; }
    }

    // stores the user-viewable contact info of the host for this event (usually admin)
    public class Hadmin
    {
        public string Name { get; set; }

        public string Phone { get; set; }

        public string Email { get; set; }
    }

    // viewable by admins and users. Editable by admins. Read by users.
    public class Hactivity : Microsoft.Azure.Documents.Resource
    {
        public string Title { get; set; }

        public string Description { get; set; }

        public string Location { get; set; }

        public DateTime Starting { get; set; }

        public DateTime Ending { get; set; }

        public List<Options> Choices { get; set; }

        public class Options
        {
            public Options()
            {
                Option = new List<string>();
            }
            public string Question { get; set; }
            public List<string> Option { get; set; }
        }

        public string ResponseId { get; set; }
    }

    /* -----------------------------------------------------------------------------------------------
        manage: handles the details for helping the admin manage the event.
            viewable by admin only
        -- herd: the users (clients) who are invited to the event
        -- responses (RSVP): the id of the activity from :event needed for the RSVP
           -- type: the type of response (e.g. dinner menu, or other activity)
           -- choices: the details to respond with for the rsvp
           -- invitees: the members who are invited to the activity
              -- response: the state of the response (i.e. not sent, sent, yes, no, maybe)
              -- choices: what the members responded with (e.g. empty or contains something from the :choices above)
           -- alerts: the reminders/notifications for the activity
              -- message:
              -- sent: the timestamp on when this alert was sent
              -- received: shows what members received this alert
       ----------------------------------------------------------------------------------------------- */

    // editable by admins. Hidden to users.
    public class Hresponse : Microsoft.Azure.Documents.Resource
    {
        // invitees' email addresses
        public List<string> Invitees { get; set; }

        public string ActivityId { get; set; }

        // list of IDs of responses from users
        public List<string> Rsvps { get; set; }

        // stores the alerts generated by the admin
        public List<string> Alerts { get; set; }

        // returns the IDs of the Hnotifications
        public List<string> Notifications { get; set; }
    }

    // editable by users. Viewable by admins.
    public class Rsvp : Microsoft.Azure.Documents.Resource
    {
        // returns the ID for the Activity
        public string ActivityId { get; set; }

        public string Email { get; set; }

        public string Answer { get; set; }

        // null = not started;
        // false = saved;
        // true = completed;
        public bool Completed { get; set; }

        // user can put descriptive info like allergy info, accessability needs, etc.
        public string Note { get; set; }
    }

    // created by the admin. Hidden to the users.
    public class Halert : Microsoft.Azure.Documents.Resource
    {
        public string HresponseId { get; set; }

        public string Message { get; set; }

        public DateTime Sent { get; set; }

        public List<string> Notified { get; set; } // Hnotifications sent
    }

    // created by admins. Viewable by users.
    public class Hnotification : Microsoft.Azure.Documents.Resource
    {
        public string AlertId { get; set; }

        public string SentTo { get; set; } // name or contact name of user

        public string Message { get; set; }

        public DateTime Sent { get; set; }

        public DateTime Received { get; set; } // timestamp from the email provider
    }
}
 